site_name: Secluso Developer Docs
theme: readthedocs
nav:
  - Home: index.md
  - Contributing: contributing.md
  - Structure (Repos):
      - core: structure/core.md
      - mobile_client:
          - Building: structure/mobile_client/building.md
          - Structure: structure/mobile_client/structure.md
      - os: structure/os.md
      - tuf-updater: structure/tuf.md
      - rpicam_apps_fork: structure/rpicam_apps_fork.md
  - Logic:
      - Reproducible Builds: logic/reproducible_builds.md
      - Reset, Toggle, IR: logic/reset_toggle_ir.md
      - MLS (E2EE): logic/mls.md
      - Motion + Object Detection: logic/detection.md
      - Notifications: logic/notifications.md
      - Pairing:
        - General Logic: logic/pairing.md
        - Bluetooth: logic/bluetooth.md
      - Testing: logic/testing.md
      - Updates:
        - Ethereum Attestation Service: logic/eas.md
        - The Update Framework (TUF): logic/tuf_updates.md
  - Hardware:
      - Raspberry Pi:
          - Pi Zero 2W: hardware/pi_zero_2w.md
          - Pi Zero W: hardware/pi_zero_w.md